#!/bin/bash
echo "This Docker container is a good Ubuntu build environment, both for x86 and ARM64 (aarch64)"
set -x
export CONTAINER=gentoo-build-container
# make user that user is in the docker group
grep -q '^docker:.*'"$USER" /etc/group || sudo usermod -aG docker "$USER"
if [ "$(id -gn)" != "docker" ]
then
    # re-exec the shell script so we are running in the docker group
    exec sudo sg docker "$0 $*"
fi
docker build -t $CONTAINER .
