#!/bin/bash
echo "This Docker container is a good Gentoo build environment, both for x86 and ARM64 (aarch64)"
set -x
export CONTAINER=gentoo-build-container
# make sure that this user is in the docker group
grep -q '^docker:.*'"$USER" /etc/group || sudo usermod -aG docker "$USER"
if [ "$(id -gn)" != "docker" ]
then
    # re-exec the shell script so we are running in the docker group
    exec sudo sg docker "$0 $*"
fi
# docker build -t $CONTAINER .
# docker run --sysctl net.ipv6.conf.all.disable_ipv6=1 --mount type=bind,source="$HOME",target=/home/user -it -u "1000:1000" --init --platform linux/arm64 --name $CONTAINER $CONTAINER /bin/bash
docker run --sysctl net.ipv6.conf.all.disable_ipv6=1 --mount type=bind,source="$HOME",target=/home/user -it -u "0:0" --init --platform linux/arm64 --name $CONTAINER $CONTAINER /bin/bash
/bin/rm -f $CONTAINER.tar
set -x
docker ps -a
set +x
echo " "
echo " "
set -x
docker container ls -a
set +x
echo " "
echo " "
set -x
docker save $CONTAINER -o "$CONTAINER.$( date +'%y%m%d_%H.%M.%S' ).tar"
set +x
echo " "
echo " "
set -x
docker container ls -a
set +x
echo "Note the container was run without --rm, you may want to: docker rm $CONTAINER"
echo "Done."
exit 0
